# Generated by Django 3.0.5 on 2020-04-24 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('fortress', models.CharField(max_length=255, verbose_name='Крепость')),
                ('description', models.TextField(verbose_name='Описание приготовление')),
                ('recipe', models.TextField(verbose_name='Рецепт')),
                ('picture', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_to', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
