# Generated by Django 3.0.6 on 2020-05-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
