# Generated by Django 3.0.6 on 2020-06-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200524_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={'verbose_name': 'коктель', 'verbose_name_plural': 'коктели'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name': 'оценка', 'verbose_name_plural': 'оценки'},
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='description',
            field=models.TextField(verbose_name='Описание приготовления'),
        ),
    ]
